import streamlit as st
from api_client import get, post

bill_key = st.session_state.get("bill_key")
if not bill_key:
    st.info("Select a bill from a candidate's **Record** tab to view details.")
    st.stop()

bill = get(f"/bills/{bill_key}")

level_badge = {"state": "🟨 State", "federal": "🟦 Federal"}.get(bill.get("level", ""), "")
meta_parts = [
    level_badge,
    bill.get("state"),
    bill.get("session") or (f"Congress {bill['congress']}" if bill.get("congress") else None),
    bill.get("bill_type", "").upper() if bill.get("bill_type") else None,
]
meta = " · ".join(str(p) for p in meta_parts if p)

st.title(f"{bill['identifier']}: {bill['title']}")
if meta:
    st.caption(meta)

if bill.get("latest_action_text"):
    st.markdown(f"**Latest action** ({bill.get('latest_action_date', '')}): "
                f"{bill['latest_action_text']}")

if bill.get("abstract"):
    st.markdown("### About")
    st.markdown(bill["abstract"])

if bill.get("url"):
    st.markdown(f"[View full text →]({bill['url']})")

st.divider()
st.subheader("AI Summary")

if bill["summary_status"] == "ready":
    st.markdown("**Plain English**")
    st.markdown(bill["plain_summary"])
    st.markdown("**ELI5**")
    st.info(bill["eli5"])
    st.caption(f"Generated by `{bill['model_id']}` · {bill['generated_at']}")
else:
    st.caption("No AI summary generated yet.")
    if st.button("Generate AI summary", type="primary"):
        with st.spinner("Asking Claude Haiku…"):
            post(f"/bills/{bill_key}/summarize")
        if hasattr(get, "clear"):
            get.clear()
        st.rerun()
